production:
  morphology: stem_en
  enable_star: true
  min_infix_len: 3
  max_matches: 10000
  mem_limit: 256M
  port: 9311
  bin_path: /usr/local/bin
  searchd_file_path: /shared/sphinx/
  config_file: /shared/config/sphinx.conf
  pid_file: /shared/pids/sphinx.pid
  address: 172.17.0.2
